---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: paymentshubrebels/bosh-utils
    tag: 'latest'

run:
  path: /bin/bash
  args:
    - -ec
    - |
      echo "No new changes, nothing to build."