---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: paymentshubrebels/bosh-utils
    tag: 'latest'

inputs:
  - name: tarball
  - name: versions

run:
  path: /bin/bash
  args:
    - -ec
    - |
      new_deployment_version=$(cat versions/versions.yml | grep _sha1)

      deployed_version_file=tarball/deployment/vars_file/versions.yml

      echo "Check if previous deployed version file exits"
      if [[ -f $deployed_version_file ]]; then
        deployed_version=$(cat $deployed_version_file | grep _sha1)
      else
        deployed_version=
      fi

      echo "compare previous deployed version and current deployment version is different"
      if [[ $deployed_version != $new_deployment_version ]]; then
        echo "Changes in releases"
      else
        echo "No Changes in the releases"
        exit 1
      fi
